VINGROUP_TICKERS  = ["VIC", "VHM", "VRE", "VPL"]
VINGROUP_GROUP    = "Vingroup Ecosystem"
EXCHANGE          = "HOSE"
PE_MIN, PE_MAX    = 0.5, 150
PB_MIN, PB_MAX    = 0.1, 30
PRICE_BOARD_BATCH = 50
FUND_BATCH_SLEEP  = 4.0
FUND_BATCH_EVERY  = 15
FUND_BATCH_PAUSE  = 45
FUND_MAX_RETRIES  = 3
FUND_RETRY_WAIT   = 90
FUND_STALE_DAYS   = 8
DATA_DIR          = "data"
DAILY_DIR         = "data/daily"
FUND_FILE         = "data/fundamentals.parquet"
TICKER_HIST_FILE  = "data/ticker_history.parquet"
SECTOR_HIST_FILE  = "data/sector_history.parquet"
DOCS_DIR          = "docs"
DASHBOARD_FILE    = "docs/index.html"
JSON_FILE         = "docs/data_latest.json"
